import { useMemo, useState } from 'react';
import FramedArtwork from '../renderer/FramedArtwork';
import { mouldings } from '../mouldings/catalog';

const mountColours={ 'Off White':'#e9e2d3', White:'#f4f2ea', Cream:'#dfd1b6', 'Light Grey':'#b9bbb7', Black:'#1e201f' };
export default function Visualiser(){
 const [sku,setSku]=useState('POL-4875'),[artWidth,setArtWidth]=useState(700),[artHeight,setArtHeight]=useState(500),[mount,setMount]=useState(50),[mountName,setMountName]=useState('Off White'),[glass,setGlass]=useState('Standard'),[lighting,setLighting]=useState('Window Left'),[view,setView]=useState('Slight Angle'),[debug,setDebug]=useState(false),[artwork,setArtwork]=useState('/assets/artwork/default.svg'),[geometryMode,setGeometryMode]=useState<'Profile'|'Flat Legacy'>('Profile'),[materialMode,setMaterialMode]=useState<'Texture'|'Clay'|'Normal'|'Wireframe'>('Texture');
 const moulding=useMemo(()=>mouldings.find(x=>x.sku===sku)!, [sku]); const outerW=artWidth+2*(mount+moulding.widthMm),outerH=artHeight+2*(mount+moulding.widthMm);
 const upload=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f)setArtwork(URL.createObjectURL(f));};
 return <main className="app"><section className="stage"><div className="brand">atelier / frame study<span>deterministic supplier asset POC</span></div><FramedArtwork moulding={moulding} artWidth={artWidth} artHeight={artHeight} mount={mount} mountColor={mountColours[mountName as keyof typeof mountColours]} glass={glass} lighting={lighting} view={view} debug={debug} artwork={artwork} geometryMode={geometryMode} materialMode={materialMode}/><div className="status">Orbit: constrained · Drag to inspect</div></section><aside className="panel"><h1>Frame Visualiser</h1><p className="subtitle">A material and proportion study for premium framed art.</p>
  <div className="group"><label>Moulding</label><select value={sku} onChange={e=>setSku(e.target.value)}>{mouldings.map(m=><option key={m.sku} value={m.sku}>{m.name} — {m.widthMm} mm</option>)}</select><div className="dimension">FACE WIDTH <b>{moulding.widthMm} mm</b><br/>PROFILE DEPTH <b>{moulding.depthMm} mm</b><br/>RESPONSE <b>{moulding.finish}</b></div></div>
  <div className="group"><label>Artwork dimensions (mm)</label><div className="row"><input aria-label="Artwork width" type="number" value={artWidth} onChange={e=>setArtWidth(+e.target.value)}/><input aria-label="Artwork height" type="number" value={artHeight} onChange={e=>setArtHeight(+e.target.value)}/></div><label style={{marginTop:12}}>Replace artwork</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></div>
  <div className="group"><label>Mount</label><select value={mountName} onChange={e=>setMountName(e.target.value)}>{Object.keys(mountColours).map(v=><option key={v}>{v}</option>)}</select><div className="chips" style={{marginTop:9}}>{[0,30,50,70].map(v=><button key={v} onClick={()=>setMount(v)} className={mount===v?'active':''}>{v===0?'No mount':`${v} mm`}</button>)}</div></div>
  <div className="group"><label>Glazing</label><div className="chips">{['None','Standard','Museum'].map(v=><button key={v} onClick={()=>setGlass(v)} className={glass===v?'active':''}>{v}</button>)}</div></div>
  <div className="group"><label>Lighting</label><select value={lighting} onChange={e=>setLighting(e.target.value)}>{['Studio Soft','Window Left','Warm Interior','Dramatic Raking Light'].map(v=><option key={v}>{v}</option>)}</select></div>
  <div className="group"><label>View</label><div className="chips">{['Front','Slight Angle','Detail'].map(v=><button key={v} onClick={()=>setView(v)} className={view===v?'active':''}>{v}</button>)}</div></div>
  <div className="group"><label>Geometry</label><div className="chips">{(['Profile','Flat Legacy'] as const).map(v=><button key={v} onClick={()=>setGeometryMode(v)} className={geometryMode===v?'active':''}>{v}</button>)}</div><label style={{marginTop:14}}>Material diagnostic</label><div className="chips">{(['Texture','Clay','Normal','Wireframe'] as const).map(v=><button key={v} onClick={()=>setMaterialMode(v)} className={materialMode===v?'active':''}>{v}</button>)}</div></div>
  <div className="group"><div className="dimension">OUTER FRAME <b>{Math.round(outerW)} × {Math.round(outerH)} mm</b><br/>MOUNT OPENING <b>{artWidth} × {artHeight} mm</b></div><button onClick={()=>setDebug(!debug)} className={debug?'active':''}>{debug?'Hide diagnostic':'Show diagnostic'}</button>{debug&&<div className="debug" style={{marginTop:10}}>SKU: {moulding.sku}<br/>PROFILE: {moulding.profileType}<br/>POINTS: {moulding.sku==='POL-4875'?'27':'n/a'}<br/>ROUGHNESS: {moulding.roughness}<br/>SHAPE: {moulding.confidence.shape}<br/>TEXTURE: {moulding.confidence.texture}</div>}{debug&&moulding.sku==='POL-4875'&&<ProfilePlot/>}</div>
 </aside></main>;
}
function ProfilePlot(){const points=[[0,15],[2,15],[3.5,21],[5,26],[7,27],[9,22],[12,19],[16,19],[20,25],[24,32],[29,38],[34,43],[40,46],[46,48],[51,48],[56,45],[61,40],[66,34],[71,29],[75,28],[79,32],[83,35],[86,31],[89,25],[92,22],[95,17],[97,16]];const path=points.map(([u,z],i)=>`${i?'L':'M'} ${12+u*2.55} ${142-z*2.45}`).join(' ');return <svg viewBox="0 0 280 165" style={{width:'100%',marginTop:10,background:'#151615',border:'1px solid #ffffff13'}}><path d="M 12 142 H 268 M 12 142 V 14" stroke="#77756e"/><path d={path} fill="none" stroke="#d8b976" strokeWidth="2"/><text x="12" y="159" fill="#aaa89e" fontSize="10">0 mm</text><text x="226" y="159" fill="#aaa89e" fontSize="10">97 mm</text><text x="15" y="25" fill="#aaa89e" fontSize="10">49 mm</text></svg>}
